/**
 * Matchup collapsed GUID / St. vs Saint / city-alias ids onto these keys.
 * Hudl TSV school_id values use the Scout/payload form; look up FridayRadar
 * schools through this map. Never invent a school from a name alone.
 */
const CANONICAL_SCHOOL_ID: Record<string, string> = {
  "fl-fort-lauderdale-st-thomas-aquinas": "fl-fort-lauderdale-saint-thomas-aquinas",
  "fl-na-carol-city-high-school": "fl-opa-locka-miami-carol-city",
  "fl-na-chaminade-madonna-college-preparatory-school": "fl-hollywood-chaminade-madonna",
  "ca-na-linda-esperanza-marquez-high-school": "ca-huntington-park-marquez",
  "ma-na-saint-john-s-prep": "ma-danvers-st-john-s-prep",
  "va-na-benedictine-college-prep": "va-richmond-benedictine",
  "nv-na-mater-academy-east-las-vegas": "nv-las-vegas-mater-academy-east",
  "al-na-mcgill-toolen-catholic-high-school": "al-mobile-mcgill-toolen",
  "mi-na-saint-mary-s-preparatory-school": "mi-orchard-lake-orchard-lake-st-mary-s",
  // NOTE: "tx-na-the-woodlands-college-park-high-school" was once aliased onto
  // tx-the-woodlands-college-park. That was wrong — ESPN files The Woodlands HS
  // recruits under College Park's name, but they are two separate schools in
  // the same town (MaxPreps a9887370… vs 06029cb1…). The record is now stored
  // with its real identity as tx-the-woodlands-the-woodlands; do not re-add it.
  "eur-na-nfl-academy": "en-london-nfl-academy",
  "tx-arlington-summit-high-school": "tx-arlington-mansfield-summit",
  "oh-warren-warren-g-harding-high-school": "oh-warren-harding",
  "tx-southlake-carroll-high-school": "tx-southlake-southlake-carroll",
  "fl-fort-lauderdale-american-heritage": "fl-plantation-american-heritage",
  "fl-windemere-first-academy": "fl-orlando-the-first-academy",
  "nj-ramsey-don-bosco-high-school": "nj-ramsey-don-bosco-prep",
  "al-montgomery-the-montgomery-academy": "al-montgomery-montgomery-academy",
  "tx-houston-c-e-king-high-school": "tx-houston-c-e-king",
  "ga-grayson-grayson": "ga-loganville-grayson",
  "md-baltimore-saint-frances-academy": "md-baltimore-st-frances-academy",
  "va-springfield-saint-james": "va-springfield-the-st-james",
  "nj-jersey-city-saint-peters-prep": "nj-jersey-city-st-peter-s-prep",
  "il-east-saint-louis-east-saint-louis": "il-east-st-louis-east-st-louis",
  "ca-bellflower-saint-john-bosco": "ca-bellflower-st-john-bosco",
  "fl-jacksonville-bolles-school": "fl-jacksonville-the-bolles-school",
  // Hudl TSV school_id aliases (verified fan.hudl.com team URLs). Unique names.
  "dc-washington-saint-johns-college": "dc-washington-st-john-s-college",
  "nj-montvale-saint-joseph-regional": "nj-montvale-st-joseph-regional",
  // Gap-fill TSV id → existing board row. Do not invent a school.
  "pa-haverford-haverford-school": "pa-haverford-the-haverford-school",
  "fl-miami-carol-city": "fl-opa-locka-miami-carol-city",
  "oh-warren-warren-g-harding": "oh-warren-harding",
  "al-hoover-spain-park": "al-birmingham-spain-park",
  "al-birmingham-a-h-parker": "al-birmingham-parker",
  "nc-haw-river-southeast-alamance": "nc-graham-southeast-alamance",
  "tx-arlington-mansfield-timberview": "tx-mansfield-mansfield-timberview",
  "md-forestville-bishop-mcnamara": "md-district-heights-bishop-mcnamara",
  "ca-fresno-clovis-west": "ca-hanford-clovis-west",
  "tx-iowa-colony-iowa-colony": "tx-rosharon-iowa-colony",
  "tx-woodlands-woodlands-college-park": "tx-the-woodlands-college-park",
  "nj-lawrenceville-lawrenceville-school": "nj-lawrenceville-the-lawrenceville-school",
  "hi-kapaa-kapaa": "hi-kapa-a-kapa-a",
  "ny-melville-saint-anthonys": "ny-long-island-city-st-anthony-s",
  "az-glendale-sandra-day-oconnor": "az-glendale-sandra-day-o-connor",
  "ca-mountain-view-saint-francis": "ca-mountain-view-st-francis",
  "il-chicago-saint-rita-of-cascia": "il-chicago-st-rita-of-cascia",
  "la-covington-saint-pauls": "la-covington-st-paul-s",
  "la-new-orleans-john-curtis": "la-river-ridge-john-curtis",
  "ma-danvers-saint-johns-prep": "ma-danvers-st-john-s-prep",
  "mo-saint-louis-christian-brothers-college": "mo-st-louis-christian-brothers-college",
  "mo-saint-louis-de-smet-jesuit": "mo-st-louis-de-smet-jesuit",
  "al-fairhope-saint-michael-catholic": "al-fairhope-st-michael-catholic",
  "al-odenville-saint-clair-county": "al-odenville-st-clair-county",
  "al-prichard-vigor": "al-mobile-vigor",
  "tx-colony-colony": "tx-the-colony-the-colony",
  "tx-waco-robinson": "tx-robinson-robinson",
  "tx-woodlands-college-park": "tx-the-woodlands-college-park",
  "tx-arlington-martin": "tx-arlington-arlington-martin",
  "tx-houston-cypress-falls": "tx-houston-cy-falls",
  "ca-bellflower-crean-lutheran": "ca-irvine-crean-lutheran",
  "ca-downey-saint-pius-x-saint-matthias-academy": "ca-downey-st-pius-x-st-matthias-academy",
  "ca-inglewood-inglewood": "ca-los-angeles-inglewood",
  "ca-long-beach-long-beach-polytechnic": "ca-long-beach-long-beach-poly",
  "ca-oneals-minarets": "ca-o-neals-minarets",
  "ca-san-diego-saint-augustine": "ca-san-diego-st-augustine",
  "ca-santa-monica-saint-monica-catholic": "ca-santa-monica-st-monica-catholic",
  "ca-stockton-saint-marys": "ca-stockton-st-mary-s",
  "ca-ventura-saint-bonaventure": "ca-ventura-st-bonaventure",
  "ct-oakdale-saint-thomas-more": "ct-oakdale-st-thomas-more",
  "ct-trumbull-saint-joseph": "ct-trumbull-st-joseph",
  "fl-boca-raton-saint-andrews": "fl-boca-raton-saint-andrew-s",
  "fl-fort-pierce-vero-beach": "fl-vero-beach-vero-beach",
  "fl-lake-minneola-first-academy": "fl-orlando-the-first-academy",
  "fl-miami-columbus": "fl-miami-miami-columbus",
  "fl-miami-miami-carol-city": "fl-opa-locka-miami-carol-city",
  "fl-miramar-saint-thomas-aquinas": "fl-fort-lauderdale-saint-thomas-aquinas",
  "fl-orlando-first-academy": "fl-orlando-the-first-academy",
  "fl-pembroke-pines-chaminade-madonna": "fl-hollywood-chaminade-madonna",
  "fl-saint-petersburg-gibbs": "fl-st-petersburg-gibbs",
  "fl-saint-petersburg-northside-christian": "fl-st-petersburg-northside-christian",
  "fl-tampa-armwood": "fl-seffner-armwood",
  "fl-villages-villages-charter": "fl-the-villages-the-villages-charter",
  "ga-atlanta-creekside": "ga-fairburn-creekside",
  "ga-atlanta-douglas-county": "ga-douglasville-douglas-county",
  "ga-college-park-woodward-academy": "ga-atlanta-woodward-academy",
  "ga-roswell-blessed-trinity": "ga-roswell-blessed-trinity-catholic",
  "ga-warner-robins-houston-county": "ga-macon-houston-county",
  "hi-honolulu-saint-louis": "hi-honolulu-st-louis-school",
  "hi-honolulu-saint-louis-school": "hi-honolulu-st-louis-school",
  "il-chicago-saint-patrick": "il-chicago-st-patrick",
  "il-evergreen-park-saint-laurence": "il-evergreen-park-st-laurence",
  "il-lombard-montini-catholic": "il-arlington-heights-montini-catholic",
  "il-oak-lawn-brother-rice": "il-chicago-brother-rice",
  "il-saint-joseph-saint-joseph-ogden": "il-st-joseph-st-joseph-ogden",
  "la-cecilia-cecilia": "la-carencro-cecilia",
  "la-new-orleans-saint-augustine": "la-new-orleans-st-augustine",
  "la-saint-francisville-west-feliciana": "la-st-francisville-west-feliciana",
  "ma-reading-tabor-academy": "ma-marion-tabor-academy",
  "md-baltimore-saint-pauls-school": "md-baltimore-st-paul-s-school",
  "mo-kansas-city-saint-pius-x": "mo-kansas-city-st-pius-x",
  "mo-lees-summit-lees-summit-north": "mo-lee-s-summit-lee-s-summit-north",
  "mo-lees-summit-lees-summit-west": "mo-lee-s-summit-lee-s-summit-west",
  "mo-saint-louis-cardinal-ritter-college-prep": "mo-st-louis-cardinal-ritter-college-prep",
  "mo-saint-louis-ladue-horton-watkins": "mo-st-louis-ladue-horton-watkins",
  "mo-saint-louis-lindbergh": "mo-st-louis-lindbergh",
  "mo-saint-louis-ritenour": "mo-st-louis-ritenour",
  "ms-diberville-diberville": "ms-d-iberville-d-iberville",
  "ms-tigers-winona-winona": "ms-winona-winona",
  "nc-saint-pauls-saint-pauls": "nc-st-pauls-st-pauls",
  "ne-hastings-saint-cecilia": "ne-hastings-st-cecilia",
  "nj-richland-saint-augustine-prep": "nj-richland-st-augustine-prep",
  "ny-hamburg-saint-francis": "ny-hamburg-st-francis",
  "ny-long-island-city-saint-anthonys": "ny-long-island-city-st-anthony-s",
  "oh-cincinnati-saint-xavier": "oh-cincinnati-st-xavier",
  "oh-cleveland-saint-ignatius": "oh-cleveland-st-ignatius",
  "oh-cleveland-villa-angela-saint-joseph": "oh-cleveland-villa-angela-st-joseph",
  "oh-columbus-saint-francis-de-sales": "oh-columbus-st-francis-de-sales",
  "oh-lakewood-saint-edward": "oh-lakewood-st-edward",
  "oh-massillon-washington": "oh-massillon-massillon-washington",
  "oh-saint-clairsville-saint-clairsville": "oh-st-clairsville-st-clairsville",
  "pa-philadelphia-la-salle-college": "pa-wyndmoor-la-salle-college",
  "pa-philadelphia-saint-josephs-prep": "pa-philadelphia-st-joseph-s-prep",
  "pa-springfield-cardinal-ohara": "pa-springfield-cardinal-o-hara",
  "pa-upper-saint-clair-upper-saint-clair": "pa-upper-st-clair-upper-st-clair",
  "sc-saint-stephen-timberland": "sc-st-stephen-timberland",
  "va-suffolk-kings-fork": "va-suffolk-king-s-fork",
  "wa-seattle-odea": "wa-seattle-o-dea",
  // Do NOT alias ca-san-mateo-junipero-serra onto Gardena Serra — different cities.
};

export function canonicalSchoolId(id: string | undefined | null): string {
  if (!id) return "";
  return CANONICAL_SCHOOL_ID[id] || id;
}
